### ISSUE TITLE
Helper functions

### ISSUE THREAD

**Issue by MarioPayan** [Audreylopez22/Redux-Payroll-Mate-Streamlit#10]
https://github.com/Audreylopez22/streamlit/blob/9b77cf0186e1b0422924c4f1cc0385ae39542ad1/rules/N_alert_inactive_person.py#L7-L12

Acabo de notar que esta función se repite en varios archivos, lo cual atenta contra DRY
Podría exisitir dentro de la misma carpeta un archivo de helpers para almacenar estas funciones para centralizar el código y evitar problemas futuros

**Comment by Audreylopez22** [comment]
Teniendo en cuenta los comentarios recibidos, se implementaron las mejoras propuestas en el código. Se abordaron y resolvieron los puntos señalados para garantizar un mejor funcionamiento y legibilidad del proyecto. Puedes revisar las mejoras detalladas en el siguiente enlace: [Enlace al Commit](https://github.com/Audreylopez22/Redux-Payroll-Mate-Streamlit/commit/dffe9cc7105c9e9e5ff1adb8de6d100e2688c8b1)
