### ISSUE TITLE
Excepciones

### ISSUE THREAD

**Issue by MarioPayan** [Audreylopez22/Redux-Payroll-Mate-Streamlit#2]
https://github.com/Audreylopez22/streamlit/blob/9b77cf0186e1b0422924c4f1cc0385ae39542ad1/pages/3_%F0%9F%8C%8D_Country_Payroll.py#L19-L48

Estas líneas de código podrían lanzar alguna excepción, ¿Correcto? debería de estar cubierto con bloques try catch y darle un manejo de excepciones adecuado

**Comment by Audreylopez22** [comment]
Teniendo en cuenta los comentarios recibidos, se implementaron las mejoras propuestas en el código. Se abordaron y resolvieron los puntos señalados para garantizar un mejor funcionamiento y legibilidad del proyecto. Puedes revisar las mejoras detalladas en el siguiente enlace: [Enlace al Commit](https://github.com/Audreylopez22/Redux-Payroll-Mate-Streamlit/commit/dffe9cc7105c9e9e5ff1adb8de6d100e2688c8b1)
