### ISSUE TITLE
Uso de linters y formateadores de código

### ISSUE THREAD

**Issue by MarioPayan** [Audreylopez22/Redux-Payroll-Mate-Streamlit#3]
https://github.com/Audreylopez22/streamlit/blob/9b77cf0186e1b0422924c4f1cc0385ae39542ad1/pages/2_%E2%9A%A0_Warnings_and_Alerts.py#L9-L13

Noto un uso inconsistente de comillas dobles y simples e inconsistencia en saltos de línea, ¿Se está usando algún linter? Sino, les recomendaría [Ruff](https://github.com/astral-sh/ruff) para resolver esto y otros problemas que sí puedan afectar el desempeño de la app a futuro

**Comment by Audreylopez22** [comment]
Se implemento el uso de [Ruff](https://github.com/astral-sh/ruff) como linter para el codigo y se establecio el formato unificado para todo el proyecto. Se evidencian los cambios en el siguiente enlace:  [Enlace al Commit](https://github.com/Audreylopez22/Redux-Payroll-Mate-Streamlit/commit/0908faf357e4d63ead4e912692b3185ac11b78db)
