### ISSUE TITLE
Contenedores

### ISSUE THREAD

**Issue by MarioPayan** [Audreylopez22/Redux-Payroll-Mate-Streamlit#4]
Parece ser que el uso de [contenedores](https://docs.streamlit.io/library/api-reference/layout/st.empty) es una buena práctica en streamlit, sería una buena idea echarle un vistazo, si no es el caso, se puede descatar este issue

**Comment by Audreylopez22** [comment]
¡Gracias por tu sugerencia! Estamos de acuerdo en que el uso de contenedores es una buena práctica en Streamlit, y tendremos en cuenta esta herramienta. Por ahora, dado el tamaño y la complejidad relativamente baja de nuestra aplicación, hemos decidido no implementar estos cambios. Sin embargo, definitivamente tendremos en cuenta tu recomendación a medida que la aplicación crezca y pueda beneficiarse más de esta estructura.
