### ISSUE TITLE
Excepciones

### ISSUE THREAD

**Issue by MarioPayan** [Audreylopez22/Redux-Payroll-Mate-Streamlit#5]
https://github.com/Audreylopez22/streamlit/blob/9b77cf0186e1b0422924c4f1cc0385ae39542ad1/pages/1_%F0%9F%93%88_Load_Sheet.py#L33-L50

El uso de excepciones también parece ser importante aquí

**Comment by Audreylopez22** [comment]
Teniendo en cuenta los comentarios recibidos, se implementaron las mejoras propuestas en el código. Se abordaron y resolvieron los puntos señalados para garantizar un mejor funcionamiento y legibilidad del proyecto. Puedes revisar las mejoras detalladas en el siguiente enlace: [Enlace al Commit](https://github.com/Audreylopez22/Redux-Payroll-Mate-Streamlit/commit/dffe9cc7105c9e9e5ff1adb8de6d100e2688c8b1)
