### ISSUE TITLE
helper functions

### ISSUE THREAD

**Issue by MarioPayan** [Audreylopez22/Redux-Payroll-Mate-Streamlit#7]
https://github.com/Audreylopez22/streamlit/blob/9b77cf0186e1b0422924c4f1cc0385ae39542ad1/pages/1_%F0%9F%93%88_Load_Sheet.py#L60-L63

Estas líneas podrían ser una función auxiliar tanto como para encapsular su comportamiento como por claridad

**Comment by Audreylopez22** [comment]
En este caso, las líneas de código mencionadas se usan solo una vez y, por lo tanto, no las hemos movido a una función auxiliar por el momento. Sin embargo, si encontramos que necesitamos utilizar este comportamiento en otro punto del código en el futuro, definitivamente consideraremos encapsularlo en una función auxiliar.
