### ISSUE TITLE
Missing page

### ISSUE THREAD

**Issue by MarioPayan** [Audreylopez22/Redux-Payroll-Mate-Streamlit#8]
https://github.com/Audreylopez22/streamlit/blob/9b77cf0186e1b0422924c4f1cc0385ae39542ad1/Home.py#L74

Esta página ya no existe pero todavía aparece dentro de la documentación inicial

**Comment by Audreylopez22** [comment]
Se elimino la información relacionada con la página Guarapo de la documentación, tal como se sugirió. Se evidencian los cambios en el siguiente enlace: [Enlace al commit](https://github.com/Audreylopez22/Redux-Payroll-Mate-Streamlit/commit/de98cbd659b5467ef12a3bc6e5440f9a6d2f7a72#diff-68de5716d94a40adc88bcb9eb3ed772ed34c1bccfbdf8b3bd0281de9c3747eea)
