### ISSUE TITLE
process_rules

### ISSUE THREAD

**Issue by MarioPayan** [Audreylopez22/Redux-Payroll-Mate-Streamlit#9]
https://github.com/Audreylopez22/streamlit/blob/9b77cf0186e1b0422924c4f1cc0385ae39542ad1/pages/1_%F0%9F%93%88_Load_Sheet.py#L33-L50

Aquí hay varias cosas.

- Se está validando dos veces que los archivos sean .py
- Tabulación poco clara (la sugerencia del linter podría resolver esto)

Para solucionar esto y otras cosas, yo recomendaría crear un diccionario de reglas que también posea el orden de de las mismas, por ejemplo:
```
rules = {
  "name": "check_birthday_alert", 
  "order": 3, 
}
```
O podría ser una lista ordenada, aunque me da la impresión de que un diccionario podría ser más útil a futuro, pero el arreglo es más rápido, dicho eso, la función podría reducirse a algo como:
```
# rules_list.py
rules [
    "check_sheets",
    "validate_sheet",
    # ...
]

# 1_📈_Load_Sheet.py
def process_rules(workbook, progress_bar):
    import rules from rules_list
    
    for i, rule in enumerate(rules):
        # Checks if file f"{rule}.py" exists

        # Rest of the logic

    return workbook
```

**Comment by Audreylopez22** [comment]
Teniendo en cuenta los comentarios recibidos, se implementaron las mejoras propuestas en el código. Se abordaron y resolvieron los puntos señalados para garantizar un mejor funcionamiento y legibilidad del proyecto. Puedes revisar las mejoras detalladas en el siguiente enlace: [Enlace al Commit](https://github.com/Audreylopez22/Redux-Payroll-Mate-Streamlit/commit/dffe9cc7105c9e9e5ff1adb8de6d100e2688c8b1)
